---
name: File-Fu
version: v0.0.3
author:
  - 'Eric Wilhelm @ <ewilhelm at cpan dot org>'
abstract: file and directory objects
license: perl
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=File-Fu
  homepage: http://scratchcomputing.com/
  license: http://dev.perl.org/licenses/
  repository: http://scratchcomputing.com/svn/File-Fu/trunk
requires:
  Class::Accessor::Classy: v0.9.0
  File::Spec: 0
  IO::File: 0
build_requires:
  Module::Build: 0.26
  Test::More: 0
provides:
  File::Fu:
    file: lib/File/Fu.pm
    version: v0.0.3
  File::Fu::Base:
    file: lib/File/Fu/Base.pm
    version: v0.0.3
  File::Fu::Dir:
    file: lib/File/Fu/Dir.pm
    version: v0.0.3
  File::Fu::Dir::FindKnob:
    file: lib/File/Fu/Dir.pm
  File::Fu::Dir::Temp:
    file: lib/File/Fu/Dir/Temp.pm
    version: v0.0.3
  File::Fu::File:
    file: lib/File/Fu/File.pm
    version: v0.0.3
  File::Fu::File::Temp:
    file: lib/File/Fu/File/Temp.pm
    version: v0.0.3
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
